// ベクター棚卸し(inventory)チェック: 各ベクター JSON の「存在すべきケース名」を
// テスト側に固定する。既存のチェックは JSON に存在するベクターを列挙して回す形の
// ため、ベクターの誤削除・rename・重複がそのまま黙って通過する(検査対象が減った
// ことを誰も検出できない)。ここで名前集合をテストコードに複製して固定し、
// JSON 側の欠落・増減を fail-closed に検出する(テストの実効性)。
//
// 運用規約: ベクターを追加・改名したらこのリストも同じ変更で更新する(意図的な
// 摩擦)。JSON 側にメタ情報(件数宣言など)を足す形は採らない — 宣言ごと改変
// されると検出できないため、固定はテスト側にのみ置く(「宣言はハードコード
// との一致を検査する」規律)。名前の照合は順序
// 非依存(ソート後の完全一致)— 並べ替えは無害だが、削除・改名・重複は落とす。

import auditHeadVectors from "../../test-vectors/audit-head.json" with { type: "json" };
import chainEntries from "../../test-vectors/chain-entries.json" with { type: "json" };
import checkpointDigest from "../../test-vectors/checkpoint-digest.json" with { type: "json" };
import dekCommitment from "../../test-vectors/dek-commitment.json" with { type: "json" };
import dekWrapSignature from "../../test-vectors/dek-wrap-signature.json" with { type: "json" };
import dekWrap from "../../test-vectors/dek-wrap.json" with { type: "json" };
import encoding from "../../test-vectors/encoding.json" with { type: "json" };
import envManifest from "../../test-vectors/env-manifest.json" with { type: "json" };
import headAttestation from "../../test-vectors/head-attestation.json" with { type: "json" };
import rfc9180Vectors from "../../test-vectors/hpke/rfc9180-base-x25519-hkdfsha256-aes256gcm.json" with { type: "json" };
import inviteAccept from "../../test-vectors/invite-accept-signature.json" with { type: "json" };
import inviteLink from "../../test-vectors/invite-link.json" with { type: "json" };
import leaseWrap from "../../test-vectors/lease-wrap.json" with { type: "json" };
import masterKeyWrap from "../../test-vectors/master-key-wrap.json" with { type: "json" };
import metaVectors from "../../test-vectors/metadata-signature.json" with { type: "json" };
import recoveryWrap from "../../test-vectors/recovery-wrap.json" with { type: "json" };
import valueSignature from "../../test-vectors/value-signature.json" with { type: "json" };
import variableEncryption from "../../test-vectors/variable-encryption.json" with { type: "json" };
import { type CheckResult, Checks } from "./support.ts";

interface NamedEntry {
  readonly name: string;
}

interface NamedCollection {
  readonly label: string;
  readonly actual: readonly NamedEntry[];
  readonly expected: readonly string[];
}

// 名前付きコレクションの固定リスト(全ベクター)。
const NAMED_COLLECTIONS: readonly NamedCollection[] = [
  {
    label: "chain-entries.valid_appends",
    actual: chainEntries.valid_appends,
    expected: [
      "readd-removed-member-same-key",
      "reuse-removed-member-key-new-user",
      "create-environment-fresh-id",
      "rotate-freshly-created-environment",
      "regrant-lease-policy-revised",
      "standalone-checkpoint-all-environments",
      "checkpoint-empty-environments",
      "listed-admin-adds-in-scope",
      "listed-admin-adds-empty-listed",
      "owner-adds-empty-listed-member",
      "listed-admin-removes-in-scope",
      "listed-admin-demotes-and-narrows",
      "listed-admin-demotes-in-scope",
      "owner-narrows-all-member",
      "listed-member-rotates-in-scope",
      "listed-member-checkpoints-in-scope",
      "owner-withdraws-others-proposal",
      "proposer-withdraws-own-proposal",
      "add-member-under-policy",
      "rotate-under-policy",
      "propose-grant-server-by-owner",
      "propose-by-listed-admin-in-scope",
      "direct-remove-after-policy-narrowed",
      "direct-remove-after-policy-off",
      "re-enable-policy-after-off",
      "member-registers-reserve-key",
      "readd-revoked-device-same-key",
      "reader-revokes-own-device",
      "other-owner-completes-after-dead-vote",
      "ci-device-rotates-in-scope",
      "ci-device-checkpoints-in-scope",
      "phone-approves-then-listed-device-added",
    ],
  },
  {
    label: "chain-entries.negative",
    actual: chainEntries.negative,
    expected: [
      "tampered-payload-role",
      "field-order-swap",
      "wrong-signer",
      "prev-hash-mismatch",
      "grant-server-scope-reorder",
      "grant-server-scope-flat-concat",
      "grant-server-lease-policy-reorder",
      "grant-server-lease-claims-reorder",
      "grant-server-lease-policy-flat-concat",
      "grant-server-lease-policy-dropped",
      "change-role-tampered-new-role",
      "revoke-server-tampered-fp",
      "create-env-tampered-commitment",
      "rotate-tampered-commitment",
      "authz-admin-grant-server",
      "authz-reader-rotate-epoch",
      "authz-nonmember-actor",
      "authz-remove-last-owner",
      "authz-demote-last-owner",
      "authz-admin-adds-admin",
      "authz-grant-scope-narrowed",
      "authz-grant-scope-narrowed-policy-revised",
      "authz-grant-role-precedes-scope-narrowed",
      "authz-grant-duplicate-server-key",
      "authz-grant-role-precedes-duplicate-server-key",
      "authz-grant-lease-policy-too-many",
      "authz-grant-lease-claims-too-many",
      "grant-lease-policy-too-many-precedes-role",
      "authz-grant-narrowed-precedes-duplicate-key",
      "authz-grant-duplicate-key-on-regrant",
      "authz-create-env-duplicate",
      "authz-rotate-unknown-environment",
      "authz-rotate-unknown-precedes-epoch",
      "authz-create-env-reader",
      "authz-create-env-role-precedes-duplicate",
      "authz-rotate-role-precedes-unknown",
      "authz-epoch-rollback",
      "authz-epoch-duplicate",
      "authz-epoch-jump",
      "authz-epoch-first-jump",
      "create-env-commitment-uppercase-hex",
      "create-env-commitment-bad-length",
      "rotate-commitment-uppercase-hex",
      "create-env-commitment-format-precedes-role",
      "authz-field-too-long",
      "authz-scope-too-many",
      "authz-add-member-duplicate-key",
      "authz-add-member-duplicate-enc-key",
      "authz-add-member-duplicate-sig-key",
      "authz-add-member-duplicate-owner-key",
      "authz-add-member-role-precedes-duplicate-key",
      "authz-add-member-duplicate-user-precedes-key",
      "authz-actor-key-mismatch",
      "authz-checkpoint-reader-role",
      "authz-checkpoint-audit-role-insufficient",
      "authz-checkpoint-role-precedes-audit-role",
      "authz-checkpoint-unknown-environment",
      "authz-checkpoint-epoch-rollback",
      "authz-checkpoint-epoch-ahead",
      "authz-checkpoint-audit-role-precedes-unknown",
      "authz-checkpoint-unknown-precedes-epoch",
      "authz-checkpoint-regression",
      "authz-checkpoint-epoch-precedes-regression",
      "checkpoint-manifest-hash-uppercase-hex",
      "checkpoint-values-digest-bad-length",
      "checkpoint-audit-head-bad-length",
      "checkpoint-duplicate-environment",
      "checkpoint-manifest-version-zero",
      "checkpoint-format-precedes-role",
      "checkpoint-tampered-environments",
      "checkpoint-environments-flat-concat",
      "add-member-scope-dropped",
      "change-role-scope-dropped",
      "add-member-scope-reorder",
      "add-member-scope-flat-concat",
      "add-member-scope-relabel-all",
      "change-role-tampered-scope",
      "policy-ops-reorder",
      "policy-ops-flat-concat",
      "policy-tampered-required",
      "propose-tampered-inner-payload",
      "propose-tampered-expires",
      "propose-inner-payload-flat",
      "approve-tampered-hash",
      "scope-all-nonempty-list",
      "scope-duplicate-id",
      "add-member-scope-too-many",
      "scope-kind-unknown",
      "scope-format-precedes-role",
      "policy-required-one",
      "policy-ops-rotate",
      "policy-ops-unknown-op",
      "policy-format-precedes-role",
      "propose-inner-op-unknown",
      "propose-inner-op-nested",
      "propose-expires-negative",
      "propose-inner-shape-precedes-role",
      "approve-hash-uppercase",
      "approve-hash-bad-length",
      "authz-add-member-unknown-scope-environment",
      "authz-add-member-owner-listed",
      "authz-change-role-owner-listed",
      "authz-add-member-scope-not-contained",
      "authz-add-member-all-scope-not-contained",
      "authz-change-role-promotion-scope-not-contained",
      "authz-change-role-widen-scope-not-contained",
      "authz-change-role-narrow-scope-not-contained",
      "authz-change-role-to-all-scope-not-contained",
      "authz-change-role-from-all-scope-not-contained",
      "authz-change-role-union-scope-not-contained",
      "authz-remove-member-scope-not-contained",
      "authz-remove-member-all-scope-not-contained",
      "authz-create-env-listed-admin",
      "authz-create-env-listed-member",
      "authz-rotate-out-of-scope",
      "authz-checkpoint-out-of-scope",
      "authz-add-member-duplicate-key-precedes-unknown-environment",
      "authz-add-member-unknown-environment-precedes-scope-role-mismatch",
      "authz-add-member-unknown-environment-precedes-scope-not-contained",
      "authz-add-member-role-precedes-scope",
      "authz-change-role-unknown-target-precedes-scope",
      "authz-change-role-last-owner-precedes-unknown-environment",
      "authz-change-role-unknown-environment-precedes-scope-not-contained",
      "authz-change-role-unknown-environment-precedes-scope-role-mismatch",
      "authz-remove-unknown-target-precedes-scope",
      "authz-rotate-unknown-precedes-out-of-scope",
      "authz-rotate-out-of-scope-precedes-epoch",
      "authz-create-env-duplicate-precedes-out-of-scope",
      "authz-checkpoint-audit-role-precedes-out-of-scope",
      "authz-checkpoint-unknown-precedes-out-of-scope",
      "authz-checkpoint-out-of-scope-precedes-epoch",
      "authz-approval-required-change-role",
      "authz-approval-required-remove-member",
      "authz-approval-required-grant-server",
      "authz-approval-required-set-approval-policy",
      "authz-approval-required-add-member-owner",
      "authz-approval-required-change-role-to-owner",
      "authz-role-precedes-approval-required",
      "authz-approval-required-precedes-unknown-target",
      "authz-approval-required-precedes-scope",
      "authz-approval-required-precedes-quorum",
      "authz-policy-role-precedes-approval-required",
      "authz-approval-required-precedes-duplicate-member",
      "authz-approval-required-precedes-duplicate-member-key",
      "authz-approval-required-precedes-duplicate-server-key",
      "authz-add-member-role-precedes-duplicate-member",
      "authz-propose-policy-off",
      "authz-propose-untargeted-op",
      "authz-propose-rotate-not-required",
      "authz-propose-role-precedes-not-required",
      "authz-propose-not-required-precedes-inner",
      "authz-propose-inner-unknown-environment",
      "authz-propose-inner-scope-not-contained",
      "authz-propose-inner-unknown-target",
      "authz-propose-inner-role",
      "authz-propose-inner-quorum-unreachable",
      "authz-policy-single-owner",
      "authz-policy-quorum-unreachable",
      "authz-approve-non-owner",
      "authz-approve-reader",
      "authz-approve-self",
      "authz-approve-expired",
      "authz-approve-unknown-hash",
      "authz-approve-applied-proposal",
      "authz-approve-withdrawn-proposal",
      "authz-withdraw-unknown-proposal",
      "authz-withdraw-closed-proposal",
      "authz-withdraw-non-proposer",
      "authz-withdraw-role-precedes-unknown",
      "authz-approve-role-precedes-unknown",
      "authz-approve-unknown-precedes-duplicate",
      "authz-approve-duplicate-owner",
      "authz-approve-proposer-removed",
      "authz-approve-expired-precedes-void",
      "authz-approve-proposer-rekeyed",
      "authz-approve-proposer-demoted",
      "authz-approve-void-precedes-inner",
      "authz-approve-inner-apply-fails",
      "authz-approve-readded-same-key-duplicate",
      "authz-approve-not-required-after-policy-change",
      "authz-approve-duplicate-precedes-not-required",
      "authz-approve-not-required-precedes-expired",
      "authz-propose-narrowed-op",
      "authz-remove-owner-quorum-unreachable",
      "authz-demote-owner-quorum-unreachable",
      "authz-propose-after-policy-off",
      "add-device-tampered-role-cap",
      "add-device-scope-relabel-all",
      "add-device-scope-reorder",
      "add-device-scope-flat-concat",
      "add-device-tampered-enc-pub",
      "revoke-device-fp-reorder",
      "revoke-device-fp-flat-concat",
      "revoke-device-tampered-target",
      "add-device-role-cap-unknown",
      "add-device-scope-all-nonempty",
      "add-device-scope-duplicate-id",
      "add-device-enc-pub-bad-length",
      "add-device-sig-pub-uppercase-hex",
      "revoke-device-empty-list",
      "revoke-device-duplicate-fp",
      "revoke-device-fp-bad-length",
      "revoke-device-too-many-fps",
      "add-device-format-precedes-actor",
      "policy-ops-add-device",
      "policy-ops-revoke-device",
      "authz-add-device-nonmember-actor",
      "authz-add-device-revoked-device-actor",
      "authz-add-device-duplicate-key-other-member",
      "authz-add-device-duplicate-own-key",
      "authz-add-device-duplicate-enc-key",
      "authz-add-device-duplicate-sig-key",
      "authz-add-device-unknown-environment",
      "authz-add-device-cap-role-exceeded",
      "authz-add-device-cap-scope-exceeded-listed",
      "authz-add-device-cap-scope-exceeded-all",
      "authz-add-device-cap-scope-exceeded-empty",
      "authz-add-device-cap-both-axes-exceeded",
      "authz-add-device-actor-not-member-precedes-duplicate-key",
      "authz-add-device-key-mismatch-precedes-duplicate-key",
      "authz-add-device-duplicate-key-precedes-unknown-environment",
      "authz-add-device-unknown-environment-precedes-cap",
      "authz-revoke-device-unknown-target",
      "authz-revoke-device-unknown-device",
      "authz-revoke-device-already-revoked",
      "authz-revoke-device-member-revokes-admin",
      "authz-revoke-device-admin-revokes-owner",
      "authz-revoke-device-reader-revokes-other",
      "authz-revoke-device-last-device-self",
      "authz-revoke-device-last-device-other",
      "authz-revoke-device-scope-not-contained",
      "authz-revoke-device-unknown-target-precedes-unknown-device",
      "authz-revoke-device-unknown-device-precedes-role",
      "authz-revoke-device-role-precedes-last-device",
      "authz-revoke-device-last-device-precedes-scope",
      "authz-revoke-device-revoked-actor",
      "authz-rotate-by-reader-cap-device",
      "authz-add-member-by-reader-cap-device",
      "authz-add-member-by-empty-scope-device",
      "authz-propose-by-empty-scope-device",
      "authz-revoke-device-by-empty-scope-device",
      "authz-rotate-out-of-device-scope",
      "authz-create-env-by-listed-device",
      "authz-checkpoint-out-of-device-scope",
      "authz-approve-revoked-device",
      "authz-approve-other-device-duplicate",
      "authz-approve-cap-below-owner",
      "authz-approve-cap-precedes-unknown-proposal",
      "authz-propose-add-device",
      "authz-propose-revoke-device",
      "authz-approve-proposer-device-revoked",
    ],
  },
  {
    label: "chain-entries.values_digests",
    actual: chainEntries.values_digests,
    expected: ["empty-set", "single-entry", "byte-ascending-order", "surrogate-boundary-order"],
  },
  {
    label: "checkpoint-digest.cases",
    actual: checkpointDigest.cases,
    expected: ["declared-excluded", "all-declared-empty"],
  },
  {
    label: "dek-commitment.vectors",
    actual: dekCommitment.vectors,
    expected: ["basic", "epoch-1-create"],
  },
  {
    label: "dek-commitment.negative",
    actual: dekCommitment.negative,
    expected: [
      "dek-mismatch",
      "transplant-project",
      "transplant-environment",
      "transplant-epoch",
      "wrong-domain",
      "uppercase-hex",
    ],
  },
  {
    label: "dek-wrap-signature.vectors",
    actual: dekWrapSignature.vectors,
    expected: ["basic", "server-basic"],
  },
  {
    label: "dek-wrap-signature.negative",
    actual: dekWrapSignature.negative,
    expected: [
      "tampered-signature",
      "tampered-ciphertext",
      "tampered-enc",
      "transplant-project",
      "transplant-environment",
      "transplant-epoch",
      "transplant-recipient",
      "recipient-key-mismatch",
      "wrong-signer-key",
      "transplant-signer",
      "suite-mismatch",
      "server-transplant-recipient-class",
      "server-transplant-fp",
      "server-recipient-key-mismatch",
    ],
  },
  {
    label: "dek-wrap.vectors",
    actual: dekWrap.vectors,
    expected: ["basic", "server-basic"],
  },
  {
    label: "dek-wrap.negative",
    actual: dekWrap.negative,
    expected: [
      "info-epoch-mismatch",
      "info-recipient-mismatch",
      "info-environment-mismatch",
      "enc-tampered",
      "server-info-member-user-id",
      "server-info-fp-mismatch",
      "member-info-server-fp",
    ],
  },
  {
    label: "encoding.cases",
    actual: encoding.cases,
    expected: [
      "ambiguity-ab-c",
      "ambiguity-a-bc",
      "empty-field",
      "empty-list",
      "utf8-multibyte",
      "number-decimal",
      "aad-shape-example",
    ],
  },
  {
    label: "env-manifest.digests",
    actual: envManifest.digests,
    expected: [
      "empty-set",
      "single-entry",
      "tombstone-entry",
      "byte-ascending-order",
      "surrogate-boundary-order",
      "declared-entry",
    ],
  },
  {
    label: "env-manifest.vectors",
    actual: envManifest.vectors,
    expected: [
      "manifest-v1-create",
      "manifest-rotate",
      "manifest-removed-issuer",
      "manifest-var-create",
      "manifest-var-rename",
      "manifest-var-delete",
      "manifest-listed-issuer-in-scope",
      "manifest-second-device-issuer-in-scope",
    ],
  },
  {
    label: "env-manifest.manifest_fork.branches",
    actual: envManifest.manifest_fork.branches,
    expected: ["manifest-fork-a", "manifest-fork-b"],
  },
  {
    label: "env-manifest.negative",
    actual: envManifest.negative,
    expected: [
      "tampered-signature",
      "tampered-digest",
      "transplant-project",
      "transplant-environment",
      "transplant-issuer",
      "wrong-issuer-key",
      "chain-head-swap",
      "chain-head-seq-mismatch",
      "suite-mismatch",
      "head-not-in-chain",
      "head-beyond-local-seq",
      "issuer-removed-at-head",
      "issuer-role-insufficient",
      "key-from-other-tenure",
      "issuer-unknown-in-history",
      "environment-not-created-at-head",
      "epoch-not-current-at-head",
      "epoch-regression",
      "v1-nonempty-prev",
      "v2-empty-prev",
      "prev-hash-mismatch",
      "digest-variable-omitted",
      "digest-tombstone-omitted",
      "digest-order-swap",
      "env-meta-mismatch",
      "composite-head-without-checkpoint-create",
      "composite-head-without-checkpoint-rotate",
      "checkpoint-binding-mismatch",
      "checkpoint-equivocation",
      "checkpoint-regressed",
      "issuer-environment-out-of-scope",
      "issuer-role-precedes-scope",
      "issuer-scope-precedes-prev",
      "issuer-device-revoked-at-head",
      "issuer-device-role-insufficient",
      "issuer-device-environment-out-of-scope",
    ],
  },
  {
    label: "head-attestation.vectors",
    actual: headAttestation.vectors,
    expected: [
      "basic",
      "reader-attestation",
      "removed-attester-in-tenure",
      "phone-attestation",
      "reader-cap-device-attestation",
    ],
  },
  {
    label: "head-attestation.negative",
    actual: headAttestation.negative,
    expected: [
      "tampered-signature",
      "transplant-project",
      "transplant-attester",
      "wrong-attester-key",
      "head-seq-mismatch",
      "suite-mismatch",
      "head-not-in-chain",
      "head-beyond-local-seq",
      "attester-removed-at-head",
      "attester-device-revoked-at-head",
    ],
  },
  {
    label: "invite-accept-signature.vectors",
    actual: inviteAccept.vectors,
    expected: ["basic"],
  },
  {
    label: "invite-accept-signature.negative",
    actual: inviteAccept.negative,
    expected: [
      "tampered-signature",
      "transplant-link-pub",
      "transplant-project",
      "transplant-invitee",
      "enc-key-mismatch",
      "sig-key-mismatch",
      "wrong-signer-key",
      "suite-mismatch",
      "legacy-domain",
    ],
  },
  {
    label: "invite-accept-signature.link_negative",
    actual: inviteAccept.link_negative,
    expected: [
      "link-tampered-signature",
      "link-wrong-link-key",
      "link-transplant-link-pub",
      "link-enc-key-mismatch",
      "link-sig-key-mismatch",
      "link-transplant-invitee",
      "link-transplant-project",
      "link-suite-mismatch",
    ],
  },
  {
    label: "invite-link.issue.vectors",
    actual: inviteLink.issue.vectors,
    expected: ["basic", "listed-scope"],
  },
  {
    label: "invite-link.issue.negative",
    actual: inviteLink.issue.negative,
    expected: [
      "tampered-signature",
      "transplant-invite-id",
      "transplant-project",
      "transplant-link-pub",
      "head-hash-swap",
      "head-seq-mismatch",
      "role-relabel",
      "inviter-enc-key-mismatch",
      "inviter-sig-key-mismatch",
      "transplant-inviter",
      "wrong-signer-key",
      "suite-mismatch",
      "scope-kind-relabel",
      "scope-environments-relabel",
      "scope-dropped",
      "scope-flat-concat",
    ],
  },
  {
    label: "invite-link.openssh.encode",
    actual: inviteLink.openssh.encode,
    expected: ["invitee-sig-key", "inviter-sig-key"],
  },
  {
    label: "invite-link.openssh.parse",
    actual: inviteLink.openssh.parse,
    expected: ["bare-line", "with-comment", "with-multiword-comment", "trailing-newline"],
  },
  {
    label: "invite-link.openssh.parse_negative",
    actual: inviteLink.openssh.parse_negative,
    expected: [
      "rsa-key",
      "security-key-ed25519",
      "uppercase-type",
      "short-key",
      "blob-type-mismatch",
      "trailing-bytes",
      "corrupt-base64",
      "missing-blob",
      "empty-line",
    ],
  },
  {
    label: "lease-wrap.vectors",
    actual: leaseWrap.vectors,
    expected: ["basic", "prior-epoch"],
  },
  {
    label: "lease-wrap.negative",
    actual: leaseWrap.negative,
    expected: [
      "info-project-mismatch",
      "info-environment-mismatch",
      "info-epoch-mismatch",
      "info-claims-digest-mismatch",
      "info-dek-wrap-domain",
    ],
  },
  {
    label: "master-key-wrap.vectors",
    actual: masterKeyWrap.vectors,
    expected: ["passkey-prf-basic", "guardian-any-2", "guardian-all-3", "handoff-guardian-share"],
  },
  {
    label: "master-key-wrap.negative",
    actual: masterKeyWrap.negative,
    expected: [
      "aad-kind-mismatch",
      "aad-wrap-ref-mismatch",
      "aad-user-mismatch",
      "aad-mode-all-as-any",
      "aad-mode-any-as-all",
      "share-missing",
      "prf-salt-mismatch",
      "suite-mismatch",
      "guardian-transplant-share-index",
      "guardian-transplant-guardian",
      "guardian-transplant-group",
      "guardian-mode-relabel",
      "handoff-transplant-request-id",
      "handoff-transplant-approver",
      "handoff-transplant-source",
      "handoff-share-index-mismatch",
      "handoff-code-checksum-mismatch",
      "handoff-code-bad-padding",
      "handoff-code-wrong-length",
      "handoff-request-id-other-key",
    ],
  },
  {
    label: "metadata-signature.vectors",
    actual: metaVectors.vectors,
    expected: [
      "var-create",
      "var-rename",
      "var-delete",
      "var-nfc-name",
      "env-create-meta",
      "env-rename",
      "env-delete-admin",
      "removed-author-in-tenure",
      "var-meta-head-before-env-create",
      "var-v2-create-typed",
      "var-v2-create-untyped",
      "var-v2-declared-create",
      "var-v2-activation",
      "var-v2-delete-keeps-schema",
      "listed-author-in-scope",
      "second-device-author-in-scope",
    ],
  },
  {
    label: "metadata-signature.rename_fork.branches",
    actual: metaVectors.rename_fork.branches,
    expected: ["rename-fork-a", "rename-fork-b"],
  },
  {
    label: "metadata-signature.name_swap.statements",
    actual: metaVectors.name_swap.statements,
    expected: ["name-swap-var-a", "name-swap-var-b"],
  },
  {
    label: "metadata-signature.name_swap.swapped",
    actual: metaVectors.name_swap.swapped,
    expected: ["name-swap-a-to-b", "name-swap-b-to-a"],
  },
  {
    label: "metadata-signature.negative",
    actual: metaVectors.negative,
    expected: [
      "tampered-signature",
      "tampered-status",
      "transplant-project",
      "transplant-environment",
      "transplant-variable",
      "transplant-meta-version",
      "transplant-signer",
      "wrong-signer-key",
      "chain-head-swap",
      "chain-head-seq-mismatch",
      "tampered-prev-hash",
      "suite-mismatch",
      "nfc-variant",
      "env-transplant-environment",
      "cross-kind-transplant",
      "head-not-in-chain",
      "head-beyond-local-seq",
      "author-removed-at-head",
      "author-role-insufficient",
      "env-delete-role-insufficient",
      "key-from-other-tenure",
      "author-unknown-in-history",
      "v1-nonempty-prev",
      "v2-empty-prev",
      "prev-hash-mismatch",
      "revive-after-delete",
      "author-environment-out-of-scope",
      "env-author-environment-out-of-scope",
      "author-role-precedes-scope",
      "author-device-revoked-at-head",
      "author-device-role-insufficient",
      "author-device-environment-out-of-scope",
      "env-author-device-environment-out-of-scope",
      "layout-confusion-v2-as-v1",
      "layout-confusion-v1-as-v2",
      "tampered-var-type",
      "tampered-required",
      "tampered-description",
      "v2-suite-mismatch",
      "declared-after-active",
      "declared-after-delete",
      "layout-regression-rename",
      "v1-declared-status",
      "v2-empty-required",
    ],
  },
  {
    label: "recovery-wrap.vectors",
    actual: recoveryWrap.vectors,
    expected: ["basic"],
  },
  {
    label: "recovery-wrap.negative",
    actual: recoveryWrap.negative,
    expected: ["aad-user-mismatch", "ciphertext-bit-flip", "wrong-salt"],
  },
  {
    label: "value-signature.vectors",
    actual: valueSignature.vectors,
    expected: [
      "v1-basic",
      "v2-chained",
      "create-head-inclusive",
      "removed-writer-in-tenure",
      "env-dev-v1",
      "rotate-head-reencryption",
      "listed-writer-in-scope",
      "second-device-writer-in-scope",
    ],
  },
  {
    label: "value-signature.fork_same_version.branches",
    actual: valueSignature.fork_same_version.branches,
    expected: ["fork-branch-a", "fork-branch-b"],
  },
  {
    label: "value-signature.negative",
    actual: valueSignature.negative,
    expected: [
      "tampered-signature",
      "tampered-ciphertext",
      "tampered-nonce",
      "transplant-project",
      "transplant-environment",
      "transplant-epoch",
      "transplant-variable",
      "transplant-version",
      "transplant-signer",
      "wrong-signer-key",
      "chain-head-swap",
      "chain-head-seq-mismatch",
      "tampered-prev-hash",
      "suite-mismatch",
      "head-not-in-chain",
      "head-beyond-local-seq",
      "writer-role-insufficient",
      "writer-removed-at-head",
      "epoch-not-current-at-head",
      "head-before-environment-create",
      "key-from-other-tenure",
      "writer-unknown-in-history",
      "v1-nonempty-prev",
      "v2-empty-prev",
      "prev-hash-mismatch",
      "epoch-regression-across-versions",
      "writer-environment-out-of-scope",
      "writer-role-precedes-scope",
      "writer-scope-precedes-epoch",
      "writer-device-revoked-at-head",
      "writer-device-role-insufficient",
      "writer-device-environment-out-of-scope",
      "writer-device-unknown-before-add",
    ],
  },
  {
    label: "variable-encryption.vectors",
    actual: variableEncryption.vectors,
    expected: ["basic"],
  },
  {
    label: "variable-encryption.negative",
    actual: variableEncryption.negative,
    expected: [
      "aad-environment-mismatch",
      "aad-epoch-mismatch",
      "ciphertext-bit-flip",
      "nonce-mismatch",
    ],
  },
];

// 名前を持たないが検査対象数として意味を持つコレクション(件数で固定)と、
// オブジェクトのキー集合で列挙されるコレクション(キー集合で固定)
const COUNTED_COLLECTIONS: readonly { label: string; actual: number; expected: number }[] = [
  { label: "chain-entries.entries", actual: chainEntries.entries.length, expected: 24 },
  {
    label: "chain-entries.expected_head_states",
    actual: chainEntries.expected_head_states.length,
    expected: 7,
  },
  { label: "audit-head.chain", actual: auditHeadVectors.chain.length, expected: 4 },
  { label: "hpke.rfc9180 vector groups", actual: rfc9180Vectors.length, expected: 1 },
];

const KEYED_COLLECTIONS: readonly {
  label: string;
  actual: readonly string[];
  expected: readonly string[];
}[] = [
  {
    label: "chain-entries.extended_chains",
    actual: Object.keys(chainEntries.extended_chains),
    expected: [
      "server-key-member-sock",
      "checkpoint-baseline",
      "proposal-one-vote",
      "proposal-completed",
      "stale-proposer-vote",
      "stale-proposer-vote-completed",
      "stale-approver-vote",
      "stale-approver-vote-completed",
      "proposer-removed",
      "proposer-rekeyed",
      "proposer-demoted",
      "proposer-removed-target-gone",
      "competing-proposals",
      "proposer-promoted",
      "proposer-promoted-self-vote",
      "proposer-promoted-completed",
      "readded-approver-vote",
      "readded-approver-revote",
      "readded-approver-same-key",
      "readded-approver-same-key-completed",
      "policy-narrowed",
      "policy-required-3",
      "policy-off",
      "device-added",
      "device-dead-vote",
      "device-revote-applied",
      "device-recovered",
      "device-ops",
      "reader-second-device",
      "proposer-device-revoked",
      "checkpoint-boundary-create",
      "checkpoint-boundary-rotate",
      "checkpoint-boundary-equivocation",
    ],
  },
  {
    label: "chain-entries.keys",
    actual: Object.keys(chainEntries.keys),
    expected: [
      "user-owner-0001",
      "user-member-0002",
      "user-admin-0003",
      "user-devmember-0010",
      "user-devadmin-0011",
      "user-prodreader-0012",
      "user-allmember-0013",
      "user-owner-0014",
      "user-owner-0015",
      "user-owner-0001@reserve",
      "user-owner-0001@phone",
      "user-allmember-0013@ci-box",
      "user-owner-0014@second",
      "user-owner-0015@reader-cap",
      "user-owner-0001@recovered",
    ],
  },
  {
    label: "master-key-wrap.guardian_keypairs",
    actual: Object.keys(masterKeyWrap.guardian_keypairs),
    expected: ["user-member-0002", "user-admin-0003", "user-guardian-0004"],
  },
  {
    label: "env-manifest.statements",
    actual: Object.keys(envManifest.statements),
    expected: [
      "note",
      "env_meta_v1",
      "api_key_v1",
      "api_key_v2_rename",
      "api_key_v3_delete",
      "legacy_v1",
      "dev_env_meta_v1",
    ],
  },
];

/** ソート後の完全一致(順序非依存)。不一致時は差分を detail に載せる。 */
function namesMatch(
  c: Checks,
  label: string,
  actual: readonly string[],
  expected: readonly string[],
): void {
  const a = actual.toSorted();
  const e = expected.toSorted();
  const ok = a.length === e.length && a.every((name, i) => name === e[i]);
  if (ok) {
    c.push(`vector inventory: ${label}`, true);
    return;
  }
  const actualSet = new Set(a);
  const expectedSet = new Set(e);
  const missing = e.filter((name) => !actualSet.has(name));
  const extra = a.filter((name) => !expectedSet.has(name));
  c.push(
    `vector inventory: ${label}`,
    false,
    `missing=[${missing.join(", ")}] extra=[${extra.join(", ")}] (dupes count toward both totals: actual ${a.length} vs expected ${e.length})`,
  );
}

export function vectorInventoryChecks(): CheckResult[] {
  const c = new Checks();
  for (const collection of NAMED_COLLECTIONS) {
    namesMatch(
      c,
      collection.label,
      collection.actual.map((entry) => entry.name),
      collection.expected,
    );
  }
  for (const counted of COUNTED_COLLECTIONS) {
    c.push(
      `vector inventory: ${counted.label} count`,
      counted.actual === counted.expected,
      counted.actual === counted.expected
        ? undefined
        : `actual ${counted.actual} vs expected ${counted.expected}`,
    );
  }
  for (const keyed of KEYED_COLLECTIONS) {
    namesMatch(c, keyed.label, keyed.actual, keyed.expected);
  }
  chainDependencyMatches(c);
  return c.results;
}

// チェーン依存の分類(CRYPTO_SPEC §11 / README 規約 27)を機械検査で守る(設計録
// es-design.md §8 K2-11-bis ①): 正規チェーンの entry_hash を 1 つでも埋め込むファイルは
// チェーン依存(正規チェーンの再生成で必ず再生成される)、埋め込まないファイルは不変。
// 分類は散文でなくここで固定する — head-attestation.json を「不変」に数えていた §11 の
// 誤りは、この検査があれば K2 のベクター先行コミットで落ちていた
const CHAIN_DEPENDENT_FILES: readonly { readonly label: string; readonly doc: unknown }[] = [
  { label: "value-signature", doc: valueSignature },
  { label: "metadata-signature", doc: metaVectors },
  { label: "env-manifest", doc: envManifest },
  { label: "head-attestation", doc: headAttestation },
  { label: "invite-link", doc: inviteLink },
];

const CHAIN_INDEPENDENT_FILES: readonly { readonly label: string; readonly doc: unknown }[] = [
  { label: "audit-head", doc: auditHeadVectors },
  { label: "checkpoint-digest", doc: checkpointDigest },
  { label: "dek-commitment", doc: dekCommitment },
  { label: "dek-wrap-signature", doc: dekWrapSignature },
  { label: "dek-wrap", doc: dekWrap },
  { label: "encoding", doc: encoding },
  { label: "hpke/rfc9180", doc: rfc9180Vectors },
  { label: "invite-accept-signature", doc: inviteAccept },
  { label: "lease-wrap", doc: leaseWrap },
  { label: "master-key-wrap", doc: masterKeyWrap },
  { label: "recovery-wrap", doc: recoveryWrap },
  { label: "variable-encryption", doc: variableEncryption },
];

/** 正規チェーン(genesis を除く — genesis hash = project_id は不変)の entry_hash を含むか。 */
function embedsCanonicalChainHash(doc: unknown): boolean {
  const text = JSON.stringify(doc);
  return chainEntries.entries
    .filter((entry) => entry.op !== "genesis")
    .some((entry) => text.includes(entry.entry_hash_hex));
}

function chainDependencyMatches(c: Checks): void {
  for (const file of CHAIN_DEPENDENT_FILES) {
    c.push(
      `vector inventory: ${file.label} is chain-dependent (embeds a canonical entry hash)`,
      embedsCanonicalChainHash(file.doc),
    );
  }
  for (const file of CHAIN_INDEPENDENT_FILES) {
    c.push(
      `vector inventory: ${file.label} is chain-independent (embeds no canonical entry hash)`,
      !embedsCanonicalChainHash(file.doc),
    );
  }
}
