// @maruhi/api-schema — HttpApi 定義(サーバー実装とクライアント導出の共有源)。
// API 境界の型は EncryptedPayload 系のみ。平文のシークレットを表す型を置かないこと。

export {
  AUDIT_ROW_ID_PATTERN,
  AuditActorSchema,
  AuditEventSchema,
  AuditEventsPageSchema,
  auditGroup,
  DEFAULT_AUDIT_EVENTS_PAGE_LIMIT,
  MAX_AUDIT_EVENTS_PAGE_LIMIT,
} from "./audit-api.ts";
export {
  AuthConfigSchema,
  authGroup,
  DeviceExchangeResultSchema,
  MAX_TOKEN_NAME_LENGTH,
  MeSchema,
  RecoveryStatusSchema,
  RecoveryWrapResultSchema,
  RecoveryWrapSchema,
  UserOrgSchema,
} from "./auth-api.ts";
export { AuthMiddleware } from "./auth-middleware.ts";
export {
  ChainActorSchema,
  ChainEntrySchema,
  CheckpointEntrySchema,
  CreateEnvironmentEntrySchema,
  RoleSchema,
  RotateEpochEntrySchema,
} from "./chain.ts";
export {
  CreateEnvironmentManifestSchema,
  CreateEnvironmentMetaStatementSchema,
  CreateVariableMetaStatementSchema,
  type DekWrapRef,
  DekWrapRefSchema,
  DeleteEnvironmentMetaStatementSchema,
  DeleteVariableMetaStatementSchema,
  type DistributedEncryptedPayload,
  DistributedEncryptedPayloadSchema,
  type DistributedEnvironmentManifest,
  DistributedEnvironmentManifestSchema,
  type DistributedEnvironmentMetaStatement,
  DistributedEnvironmentMetaStatementSchema,
  type DistributedVariableMetaStatement,
  DistributedVariableMetaStatementSchema,
  type EncryptedPayload,
  EncryptedPayloadSchema,
  type EnvironmentManifest,
  EnvironmentManifestSchema,
  type LeasedDek,
  LeasedDekSchema,
  type RecipientDek,
  RecipientDekSchema,
  RenameEnvironmentMetaStatementSchema,
  RenameVariableMetaStatementSchema,
  VariableAadSchema,
  type WrappedDek,
  WrappedDekSchema,
} from "./data.ts";
export {
  deksGroup,
  EnvironmentChainResultSchema,
  EnvironmentMetadataPullSchema,
  EnvironmentPullSchema,
  environmentsGroup,
  EnvironmentSummarySchema,
  PulledVariableSchema,
  variablesGroup,
  VariableVersionSchema,
} from "./data-api.ts";
export {
  InvitationSummarySchema,
  InviteAcceptanceSchema,
  InviteAcceptResultSchema,
  InviteIssueResultSchema,
  InviteRoleSchema,
  invitesGroup,
  InviteStatusSchema,
  InviteTokenSchema,
} from "./invites-api.ts";
export { leaseGroup, LeaseRequestSchema, LeaseResponseSchema } from "./lease-api.ts";
export {
  RotationDismissTargetSchema,
  RotationFlagBasisSchema,
  RotationFlagSchema,
  rotationGroup,
} from "./rotation-api.ts";
export {
  AuthFlowError,
  AuthFlowFailureReasonSchema,
  AuthRateLimitedError,
  ChainCapacityExceededError,
  ChainEntryInvalidError,
  ChainEntryTooLargeError,
  ChainHeadConflictError,
  ChainInvalidReasonSchema,
  CheckpointStateMismatchError,
  CompositeRequiredError,
  DataLimitExceededError,
  DataLimitResourceSchema,
  DekWrapExistsError,
  DekWrapNotFoundError,
  DekWrapRejectedError,
  DekWrapRejectReasonSchema,
  EnvironmentConflictError,
  EnvironmentConflictReasonSchema,
  EnvironmentNotFoundError,
  EpochConflictError,
  ForbiddenError,
  ForbiddenReasonSchema,
  InviteGoneError,
  InviteGoneReasonSchema,
  InviteNotFoundError,
  InvitePendingLimitError,
  InviteRateLimitedError,
  InviteSignatureInvalidError,
  LeaseRateLimitedError,
  LeaseRateLimitScopeSchema,
  LeaseUnauthorizedError,
  LeaseUnauthorizedReasonSchema,
  LeaseUnavailableError,
  LeaseUnavailableReasonSchema,
  ManifestRejectedError,
  ManifestRejectReasonSchema,
  ManifestVersionConflictError,
  MetaStatementRejectedError,
  MetaVersionConflictError,
  NameNotNfcError,
  PayloadMismatchError,
  ProjectAlreadyInitializedError,
  ProjectNotFoundError,
  RecoveryRateLimitedError,
  RecoveryWrapNotFoundError,
  ResourceConflictReasonSchema,
  RotationFlagNotFoundError,
  SetupIncompleteError,
  SetupIncompleteReasonSchema,
  TokenLimitError,
  UnauthorizedError,
  ValueSignatureRejectedError,
  ValueSignatureRejectReasonSchema,
  ValueTooLargeError,
  VariableConflictError,
  VariableNotFoundError,
  VersionConflictError,
} from "./errors/index.ts";
export {
  ChainHeadSchema,
  ChainSnapshotSchema,
  maruhiApi,
  membershipGroup,
} from "./membership-api.ts";
export {
  assertSecurityCriticalPayloadsStrict,
  assertStrictPayloadRoot,
  SECURITY_CRITICAL_PAYLOAD_ENDPOINTS,
  STRICT_EXEMPT_PAYLOAD_ENDPOINTS,
  strictPayload,
} from "./strict.ts";
