// @maruhi/api-schema — HttpApi 定義(サーバー実装とクライアント導出の共有源)。
// API 境界の型は EncryptedPayload 系のみ。平文のシークレットを表す型を置かないこと。

export {
  AUDIT_ROW_ID_PATTERN,
  AuditActorSchema,
  AuditEventSchema,
  AuditEventsPageSchema,
  auditGroup,
  AuditHeadSchema,
  DEFAULT_AUDIT_EVENTS_PAGE_LIMIT,
  MAX_AUDIT_EVENTS_PAGE_LIMIT,
} from "./audit-api.ts";
export {
  AuthConfigSchema,
  authGroup,
  DEFAULT_TOKEN_TTL_DAYS,
  MAX_TOKEN_NAME_LENGTH,
  MAX_TOKEN_TTL_DAYS,
  MeSchema,
  RecoveryStatusSchema,
  RecoveryWrapResultSchema,
  RecoveryWrapSchema,
  SignupCodeSchema,
  type SignupPolicy,
  SignupPolicySchema,
  TOKEN_NAME_FORBIDDEN_CHARS,
  TokenListSchema,
  TokenNameSchema,
  TokenSummarySchema,
  UserOrgSchema,
} from "./auth-api.ts";
export {
  authCliGroup,
  CliFlowIdSchema,
  CliPollApprovedSchema,
  CliPollDeniedSchema,
  CliPollPendingSchema,
  CliPollResultSchema,
  CliStartResultSchema,
  MIN_CLI_POLL_INTERVAL_SECONDS,
} from "./auth-cli-api.ts";
export { AuthMiddleware, CSRF_HEADER_NAME } from "./auth-middleware.ts";
export {
  ChainActorSchema,
  ChainEntrySchema,
  CheckpointEntrySchema,
  CreateEnvironmentEntrySchema,
  RoleSchema,
  RotateEpochEntrySchema,
} from "./chain.ts";
export {
  ActivateVariableMetaStatementSchema,
  type CheckpointValueSnapshot,
  type CheckpointValueSnapshotEntry,
  CheckpointValueSnapshotEntrySchema,
  CheckpointValueSnapshotSchema,
  CreateEnvironmentManifestSchema,
  CreateEnvironmentMetaStatementSchema,
  CreateVariableMetaStatementSchema,
  CreateVariableMetaStatementV2Schema,
  DeclareVariableMetaStatementSchema,
  type DekWrapRef,
  DekWrapRefSchema,
  DeleteEnvironmentMetaStatementSchema,
  DeleteVariableMetaStatementSchema,
  DeleteVariableMetaStatementV2Schema,
  type DistributedEncryptedPayload,
  DistributedEncryptedPayloadSchema,
  type DistributedEnvironmentManifest,
  DistributedEnvironmentManifestSchema,
  type DistributedEnvironmentMetaStatement,
  DistributedEnvironmentMetaStatementSchema,
  type DistributedVariableMetaStatement,
  DistributedVariableMetaStatementSchema,
  type EncryptedPayload,
  EncryptedPayloadSchema,
  type EnvironmentManifest,
  EnvironmentManifestSchema,
  type LeasedDek,
  LeasedDekSchema,
  MetaVarTypeSchema,
  type RecipientDek,
  RecipientDekSchema,
  RenameEnvironmentMetaStatementSchema,
  RenameVariableMetaStatementSchema,
  RenameVariableMetaStatementV2Schema,
  type SchemaPolicy,
  SchemaPolicySchema,
  VariableAadSchema,
  type WrappedDek,
  WrappedDekSchema,
} from "./data.ts";
export {
  deksGroup,
  EnvironmentChainResultSchema,
  EnvironmentMetadataPullSchema,
  EnvironmentPullSchema,
  environmentsGroup,
  EnvironmentSummarySchema,
  PulledVariableSchema,
  schemaPolicyGroup,
  variablesGroup,
  VariableVersionSchema,
} from "./data-api.ts";
export {
  InvitationSummarySchema,
  InviteAcceptanceSchema,
  InviteAcceptResultSchema,
  InviteIssueResultSchema,
  InviteRoleSchema,
  invitesGroup,
  InviteStatusSchema,
  InviteTokenSchema,
} from "./invites-api.ts";
export { leaseGroup, LeaseRequestSchema, LeaseResponseSchema } from "./lease-api.ts";
export {
  RotationDismissTargetSchema,
  RotationFlagBasisSchema,
  RotationFlagSchema,
  rotationGroup,
} from "./rotation-api.ts";
export {
  ActivationRequiredError,
  AttestationRateLimitedError,
  AttestationRegressionError,
  AttestationRejectedError,
  AttestationRejectReasonSchema,
  AuditHeadNotReadyError,
  AuthFlowError,
  AuthFlowFailureReasonSchema,
  AuthRateLimitedError,
  ChainCapacityExceededError,
  ChainEntryInvalidError,
  ChainEntryTooLargeError,
  ChainHeadConflictError,
  ChainInvalidReasonSchema,
  CheckpointMismatchReasonSchema,
  CheckpointStateMismatchError,
  CliFlowExpiredError,
  CliFlowRejectedError,
  CompositeRequiredError,
  DataLimitExceededError,
  DataLimitResourceSchema,
  DekWrapExistsError,
  DekWrapNotFoundError,
  DekWrapRejectedError,
  DekWrapRejectReasonSchema,
  EnvironmentConflictError,
  EnvironmentConflictReasonSchema,
  EnvironmentNotFoundError,
  EpochConflictError,
  ForbiddenError,
  ForbiddenReasonSchema,
  InviteGoneError,
  InviteGoneReasonSchema,
  InviteNotFoundError,
  InvitePendingLimitError,
  InviteRateLimitedError,
  InviteSignatureInvalidError,
  LeaseRateLimitedError,
  LeaseRateLimitScopeSchema,
  LeaseUnauthorizedError,
  LeaseUnauthorizedReasonSchema,
  LeaseUnavailableError,
  LeaseUnavailableReasonSchema,
  ManifestRejectedError,
  ManifestRejectReasonSchema,
  ManifestVersionConflictError,
  MetaStatementRejectedError,
  MetaStatementRejectReasonSchema,
  MetaVersionConflictError,
  NameNotNfcError,
  PayloadMismatchError,
  ProjectAlreadyInitializedError,
  ProjectLimitError,
  ProjectNotFoundError,
  RecoveryRateLimitedError,
  RecoveryWrapNotFoundError,
  ResourceConflictReasonSchema,
  RotationFlagNotFoundError,
  SchemaDescriptionRejectedError,
  SchemaDescriptionRejectReasonSchema,
  SchemaPolicyRejectedError,
  SchemaPolicyRejectReasonSchema,
  SetupIncompleteError,
  SetupIncompleteReasonSchema,
  TokenLimitError,
  TokenNotFoundError,
  UnauthorizedError,
  ValueSignatureRejectedError,
  ValueSignatureRejectReasonSchema,
  ValueTooLargeError,
  VariableConflictError,
  VariableNotFoundError,
  VersionConflictError,
} from "./errors/index.ts";
export {
  ChainHeadSchema,
  ChainSnapshotSchema,
  DistributedHeadAttestationSchema,
  HeadAttestationSubmissionSchema,
  maruhiApi,
  membershipGroup,
  ProjectListSchema,
  ProjectMembershipSchema,
} from "./membership-api.ts";
export {
  assertSessionCapabilityClassified,
  isSessionAllowedEndpoint,
  SESSION_ALLOWED_ENDPOINTS,
  UNAUTHENTICATED_ENDPOINTS,
} from "./session-capability.ts";
export {
  assertSecurityCriticalPayloadsStrict,
  assertStrictPayloadRoot,
  SECURITY_CRITICAL_PAYLOAD_ENDPOINTS,
  STRICT_EXEMPT_PAYLOAD_ENDPOINTS,
  strictPayload,
} from "./strict.ts";
