// @maruhi/api-schema — HttpApi 定義(サーバー実装とクライアント導出の共有源)。
// API 境界の型は EncryptedPayload 系のみ。平文のシークレットを表す型を置かないこと。

export {
  AuthConfigSchema,
  authGroup,
  DeviceExchangeResultSchema,
  MeSchema,
  RecoveryStatusSchema,
  RecoveryWrapResultSchema,
  RecoveryWrapSchema,
  UserOrgSchema,
} from "./auth-api.ts";
export { AuthMiddleware } from "./auth-middleware.ts";
export {
  ChainActorSchema,
  ChainEntrySchema,
  CreateEnvironmentEntrySchema,
  RoleSchema,
  RotateEpochEntrySchema,
} from "./chain.ts";
export {
  CreateEnvironmentMetaStatementSchema,
  CreateVariableMetaStatementSchema,
  type DekWrapRef,
  DekWrapRefSchema,
  DeleteEnvironmentMetaStatementSchema,
  DeleteVariableMetaStatementSchema,
  type DistributedEncryptedPayload,
  DistributedEncryptedPayloadSchema,
  type DistributedEnvironmentMetaStatement,
  DistributedEnvironmentMetaStatementSchema,
  type DistributedVariableMetaStatement,
  DistributedVariableMetaStatementSchema,
  type EncryptedPayload,
  EncryptedPayloadSchema,
  type LeasedDek,
  LeasedDekSchema,
  type RecipientDek,
  RecipientDekSchema,
  RenameEnvironmentMetaStatementSchema,
  RenameVariableMetaStatementSchema,
  VariableAadSchema,
  type WrappedDek,
  WrappedDekSchema,
} from "./data.ts";
export {
  deksGroup,
  EnvironmentChainResultSchema,
  EnvironmentMetadataPullSchema,
  EnvironmentPullSchema,
  environmentsGroup,
  EnvironmentSummarySchema,
  PulledVariableSchema,
  variablesGroup,
  VariableVersionSchema,
} from "./data-api.ts";
export { leaseGroup, LeaseRequestSchema, LeaseResponseSchema } from "./lease-api.ts";
export {
  AuthFlowError,
  AuthFlowFailureReasonSchema,
  ChainCapacityExceededError,
  ChainEntryInvalidError,
  ChainEntryTooLargeError,
  ChainHeadConflictError,
  ChainInvalidReasonSchema,
  CompositeRequiredError,
  DataLimitExceededError,
  DataLimitResourceSchema,
  DekWrapExistsError,
  DekWrapNotFoundError,
  DekWrapRejectedError,
  DekWrapRejectReasonSchema,
  EnvironmentConflictError,
  EnvironmentConflictReasonSchema,
  EnvironmentNotFoundError,
  EpochConflictError,
  ForbiddenError,
  ForbiddenReasonSchema,
  LeaseRateLimitedError,
  LeaseUnauthorizedError,
  LeaseUnauthorizedReasonSchema,
  LeaseUnavailableError,
  LeaseUnavailableReasonSchema,
  MetaStatementRejectedError,
  MetaVersionConflictError,
  NameNotNfcError,
  PayloadMismatchError,
  ProjectAlreadyInitializedError,
  ProjectNotFoundError,
  RecoveryRateLimitedError,
  RecoveryWrapNotFoundError,
  ResourceConflictReasonSchema,
  SetupIncompleteError,
  SetupIncompleteReasonSchema,
  TokenLimitError,
  UnauthorizedError,
  ValueSignatureRejectedError,
  ValueSignatureRejectReasonSchema,
  ValueTooLargeError,
  VariableConflictError,
  VariableNotFoundError,
  VersionConflictError,
} from "./errors/index.ts";
export {
  ChainHeadSchema,
  ChainSnapshotSchema,
  maruhiApi,
  membershipGroup,
} from "./membership-api.ts";
