// HttpApi definition of rotation-required flags (AUDIT_SPEC §4.1 / §6 /
// §7 — Wave 2 B2).
//
// - flags: a standalone derived view (§7) in which the server computes
//   and returns the §4.1 step-5 derivation (currently effective
//   recommended − resolution events). Visibility is class 1 (chain role
//   reader or higher = all members — §6; detection exists to prompt
//   upstream-credential rotation and would not work admin-only)
// - dismiss: the dedicated operation endpoint for rotation.dismissed
//   (§7 — no raw-event append API exists; events are generated by
//   server-side processing). admin or higher × admin scope (the §3.3
//   recording rule)
//
// Responses carry identifiers only (the client resolves display names
// via verified meta statements — tombstones included; AUDIT_SPEC §7).

import { EnvironmentIdSchema, ProjectIdSchema, VariableIdSchema } from "@maruhi/core";
import { Schema } from "effect";
import { HttpApiEndpoint, HttpApiGroup, HttpApiSchema } from "effect/http-api";

import { AuthMiddleware } from "./auth-middleware.ts";
import {
  DataLimitExceededError,
  ForbiddenError,
  ProjectNotFoundError,
  RotationFlagNotFoundError,
} from "./errors/index.ts";
import { KeyFingerprintHex, PositiveInt } from "./hex.ts";

/**
 * Evidence rank of a rotation flag (AUDIT_SPEC §4.1 step 3): `read` = the
 * removed subject verifiably fetched the ciphertext during a membership /
 * grant interval, `readable` = it could have.
 */
export const RotationFlagBasisSchema = Schema.Literals(["read", "readable"]);

/**
 * Which chain operation produced a rotation flag (AUDIT_SPEC §3.3
 * `rotation.recommended` payload.trigger — 2026-09-14 ES): `remove_member`,
 * `change_role` (demotion below member, or a scope narrowing — the
 * `change_role` variant of §4.1) or `revoke_server`.
 */
export const RotationFlagTriggerSchema = Schema.Literals([
  "remove_member",
  "change_role",
  "revoke_server",
  // Device revocation (the AUDIT_SPEC §4.1 revoke_device variant — 2026-09-19 DK K3)
  "revoke_device",
]);

/**
 * One currently-effective `rotation.recommended` event (AUDIT_SPEC §3.3 —
 * one row per (variable × environment)). Exactly one of `targetUserId`
 * (remove_member variant) / `targetServerKeyFingerprintHex` (revoke_server
 * variant) is present. `triggerChainSeq` is the chain seq of the removal /
 * role-change / revocation entry that produced the flag; `trigger` names that
 * operation.
 *
 * No audit seq is carried (AUDIT_SPEC §7): the ordinal of gapless
 * numbering would leak the count of class-2 rows, so it does not
 * appear even on the class-1 view. The seq-order judgement of
 * resolution (§4.1 step 5) is a server-internal derivation; the
 * display order needs only recommendedAtMs.
 */
export const RotationFlagSchema = Schema.Struct({
  environmentId: EnvironmentIdSchema,
  variableId: VariableIdSchema,
  basis: RotationFlagBasisSchema,
  targetUserId: Schema.optionalKey(Schema.String),
  targetServerKeyFingerprintHex: Schema.optionalKey(KeyFingerprintHex),
  recommendedAtMs: Schema.Number,
  triggerChainSeq: PositiveInt,
  trigger: RotationFlagTriggerSchema,
  /**
   * Present when the flag had been resolved and is effective again because
   * the push of this version restored a value from before the flag
   * (AUDIT_SPEC §4.1 procedure 5's lineage derivation / §7 — 2026-09-27 VH).
   * A later re-encryption of the restored value keeps it.
   */
  reopenedByVersion: Schema.optionalKey(PositiveInt),
});

/** GET /projects/:projectId/rotation/flags: the project's active rotation flags (AUDIT_SPEC §7). */
export const RotationFlagListSchema = Schema.Struct({
  flags: Schema.Array(RotationFlagSchema),
});

/** One (environment, variable) dismissal target (AUDIT_SPEC §7). */
export const RotationDismissTargetSchema = Schema.Struct({
  environmentId: EnvironmentIdSchema,
  variableId: VariableIdSchema,
});

export const rotationGroup = HttpApiGroup.make("rotation")
  .add(
    HttpApiEndpoint.get("flags", "/projects/:projectId/rotation/flags", {
      params: { projectId: ProjectIdSchema },
      success: RotationFlagListSchema,
      error: [ProjectNotFoundError, ForbiddenError],
    }).middleware(AuthMiddleware),
  )
  .add(
    HttpApiEndpoint.post("dismiss", "/projects/:projectId/rotation/dismissals", {
      params: { projectId: ProjectIdSchema },
      // An empty enumeration is a Schema-validation 400 (meaningless as
      // the call shape of an operation that leaves an audit trail —
      // same "never silently succeed" discipline as deks.remove)
      payload: Schema.Struct({
        targets: Schema.Array(RotationDismissTargetSchema).check(Schema.isMinLength(1)),
      }),
      success: HttpApiSchema.NoContent,
      error: [
        ProjectNotFoundError,
        ForbiddenError,
        // Dismissal aimed at a pair with no effective flag (all-or-nothing refuses the whole thing)
        RotationFlagNotFoundError,
        DataLimitExceededError,
      ],
    }).middleware(AuthMiddleware),
  );
