// @maruhi/core — domain types, Effect Schema, shared logic.
// The bridge between crypto (Effect-free) and the upper layers
// (Effect-based) happens here.

export {
  ChainInvalidError,
  CryptoContractViolationError,
  CryptoDecryptError,
  CryptoDekCommitmentError,
  CryptoDekUnwrapError,
  CryptoDekWrapError,
  CryptoDekWrapSignatureError,
  CryptoEncryptError,
  cryptoEffect,
  CryptoEnvManifestInvalidError,
  CryptoHeadAttestationInvalidError,
  CryptoInvalidInputError,
  CryptoInviteAcceptSignatureError,
  CryptoInviteIssueSignatureError,
  CryptoInviteLinkSignatureError,
  CryptoKeyExportError,
  CryptoKeyImportError,
  CryptoMetaStatementInvalidError,
  cryptoPromise,
  type CryptoPromiseOperation,
  CryptoRejectedError,
  CryptoSignError,
  CryptoUnsupportedMetaLayoutError,
  CryptoValueInvalidError,
  fromCryptoResult,
  toWrappedCryptoError,
  type WrappedCryptoError,
} from "./crypto-errors.ts";
export { type EgressRequestInit, egressHttpClientLayer } from "./egress.ts";
export { ulid } from "./ids.ts";
export {
  decodeKeyFingerprintHex,
  decodeProviderUserId,
  decodeUserId,
  type KeyFingerprintHex,
  KeyFingerprintHexSchema,
  type ProviderUserId,
  ProviderUserIdSchema,
  serverKeyFingerprintHex,
  type UserId,
  UserIdSchema,
  userKeyFingerprintHex,
} from "./identity.ts";
export {
  assertProjectAuditPayload,
  assertUserOrgAuditPayload,
  type ChainMirrorEventName,
  type ProjectAuditEventName,
  type ProjectAuditEventPayload,
  LEASE_DENIAL_REASONS,
  type LeaseDenialReason,
  ROTATION_BASES,
  ROTATION_CONNECTORS,
  ROTATION_TRIGGERS,
  type UserOrgAuditEventPayload,
} from "./audit-payloads.ts";
export {
  type AuditActor,
  auditActorOf,
  type AuditEventColumns,
  type AuditEventRecord,
  type AuditEventRecordOf,
  auditPayloadWith,
  type AuditReadPayload,
  auditReadPayload,
  type AuditReadVariable,
  auditReadVariablesOf,
  CHAIN_MIRROR_EVENT_PREFIX,
  CHAIN_MIRROR_EVENTS,
  chainMirrorEvents,
  type ChainMirrorSubject,
  type IndexedProposal,
  indexProposals,
  type ProposalIndex,
  type ProposeEntry,
  VAR_READ_EVENT,
} from "./audit.ts";
export {
  anonymousPrincipal,
  type AuthenticatedPrincipal,
  type IssuedSession,
  type IssuedToken,
  type OrgRole,
  AUTH_FLOW_FAILURE_REASONS,
  AUTH_METHODS,
  type AuthMethod,
  OrgRoleSchema,
  SIGNUP_DENIAL_REASONS,
  type SignupDenialReason,
  parseTokenScopes,
  permissionAtLeast,
  type Principal,
  RequestAuth,
  type RequestAuthShape,
  scopePermissionFor,
  SessionService,
  type SessionServiceShape,
  TokenLimitReachedError,
  type TokenPermission,
  TokenPermissionSchema,
  type TokenScope,
  TokenScopeSchema,
  TokenService,
  type TokenServiceShape,
} from "./auth.ts";
export {
  type EnvironmentId,
  EnvironmentIdSchema,
  isEnvironmentId,
  isProjectId,
  isVariableId,
  type ProjectId,
  ProjectIdSchema,
  type VariableId,
  VariableIdSchema,
} from "./project.ts";
