// @maruhi/core — ドメイン型、Effect Schema、共有ロジック。
// crypto(Effect 非依存)と上位層(Effect ベース)の橋渡しはここで行う。

export {
  ChainInvalidError,
  CryptoDecryptError,
  CryptoDekCommitmentError,
  CryptoDekUnwrapError,
  CryptoDekWrapError,
  CryptoDekWrapSignatureError,
  CryptoEncryptError,
  cryptoEffect,
  CryptoInvalidInputError,
  CryptoKeyExportError,
  CryptoKeyImportError,
  CryptoMetaStatementInvalidError,
  CryptoSignError,
  CryptoValueInvalidError,
  fromCryptoResult,
  toWrappedCryptoError,
  type WrappedCryptoError,
} from "./crypto-errors.ts";
export { type AuditActor, auditActorOf, auditPayloadWith } from "./audit.ts";
export {
  anonymousPrincipal,
  type AuthenticatedPrincipal,
  type IssuedSession,
  type IssuedToken,
  type OrgRole,
  OrgRoleSchema,
  parseTokenScopes,
  permissionAtLeast,
  type Principal,
  RequestAuth,
  type RequestAuthShape,
  scopePermissionFor,
  SessionService,
  type SessionServiceShape,
  TokenLimitReachedError,
  type TokenPermission,
  TokenPermissionSchema,
  type TokenScope,
  TokenScopeSchema,
  TokenService,
  type TokenServiceShape,
} from "./auth.ts";
export {
  type EnvironmentId,
  EnvironmentIdSchema,
  isEnvironmentId,
  isProjectId,
  isVariableId,
  type ProjectId,
  ProjectIdSchema,
  type VariableId,
  VariableIdSchema,
} from "./project.ts";
