// apex サイト(LP + docs — Blume)のテーマ生成(裁定 B — docs/notes/web-design-pass.md §4
// 「DP2 実装時の裁定録」)。
//
// ブランド定義の唯一の置き場所は apps/web/theme/(ADR-0013)。その生成物 maruhi.css
// (`astryx theme build` の出力 — 朱 2 値 + on-accent 2 値は tokens で確定、warm neutral は
// HCT 導出)から、Blume の theme tokens(`--blume-*`)と blume.config.ts が読む定数を
// **書き出す**。site 側に生 hex を手で書かない(二重管理を作らない)ため、生成物は
// コミットし、test/unit/theme.test.ts が「再生成 = コミット済み」を検査する(DP1 の
// 「生成 CSS と一致」契約と同じ型)。
//
// 同じ経路でブランド資産(favicon / logo / OG / apple-touch-icon)を apps/web/public から
// 複製し、ダークモード用のロゴ(fill を dark accent に差し替えた SVG)を導出する。
import { readFileSync } from "node:fs";
import { join } from "node:path";

/** 光・闇の 2 値。 */
export interface ModePair {
  readonly light: string;
  readonly dark: string;
}

/** maruhi.css から抽出したブランドトークン(すべて hex)。 */
export interface BrandTokens {
  readonly accent: ModePair;
  readonly onAccent: ModePair;
  readonly background: ModePair;
  readonly surface: ModePair;
  readonly popover: ModePair;
  readonly foreground: ModePair;
  readonly mutedForeground: ModePair;
  readonly border: ModePair;
  readonly radius: string;
}

/** リポジトリ相対パス(生成の入力・出力の目録)。 */
export const paths = {
  /** 入力: Astryx テーマの生成 CSS(ブランドの正の生成物)。 */
  webThemeCss: "apps/web/theme/maruhi.css",
  /** 入力: 朱の単色ロゴ(light 側の accent で塗られている)。 */
  webLogo: "apps/web/public/logo.svg",
  /** 出力: Blume の theme.css(design tokens の上書き)。 */
  themeCss: "apps/site/theme.css",
  /** 出力: blume.config.ts が読む定数。 */
  tokensTs: "apps/site/theme/tokens.ts",
  /** 出力: ダークモード用ロゴ(fill を dark accent へ)。 */
  logoDark: "apps/site/public/logo-dark.svg",
} as const;

/** apps/web/public から apps/site/public へ無変換で複製するブランド資産。 */
export const copiedAssets = ["favicon.svg", "logo.svg", "og.png", "apple-touch-icon.png"] as const;

const HEX = "#[0-9a-fA-F]{6}(?:[0-9a-fA-F]{2})?";

/**
 * `--<token>: light-dark(<hex>, <hex>)` の宣言を maruhi.css から 1 組だけ取り出す。
 * 同じトークン名は variant スコープで `var(...)` 参照として再宣言されるため、
 * hex の light-dark 形に限って一意であることを要求する(複数の異なる組が出たら
 * 生成規則の前提が変わったとみなして失敗させる)。
 */
function pickPair(css: string, token: string): ModePair {
  const re = new RegExp(`--${token}:\\s*light-dark\\((${HEX}),\\s*(${HEX})\\)`, "g");
  const pairs = new Set<string>();
  for (const m of css.matchAll(re)) pairs.add(`${m[1]!.toLowerCase()} ${m[2]!.toLowerCase()}`);
  if (pairs.size !== 1) {
    throw new Error(
      `apps/web/theme/maruhi.css: expected exactly one light-dark hex pair for --${token}, found ${pairs.size}`,
    );
  }
  const [light, dark] = [...pairs][0]!.split(" ") as [string, string];
  return { light: light.toUpperCase(), dark: dark.toUpperCase() };
}

function pickLength(css: string, token: string): string {
  const values = new Set(
    [...css.matchAll(new RegExp(`--${token}:\\s*([0-9.]+(?:rem|px))`, "g"))].map((m) => m[1]!),
  );
  if (values.size !== 1) {
    throw new Error(
      `apps/web/theme/maruhi.css: expected exactly one value for --${token}, found ${values.size}`,
    );
  }
  return [...values][0]!;
}

/** maruhi.css の本文からブランドトークンを抽出する。 */
export function extractBrand(webThemeCss: string): BrandTokens {
  return {
    accent: pickPair(webThemeCss, "color-accent"),
    onAccent: pickPair(webThemeCss, "color-on-accent"),
    background: pickPair(webThemeCss, "color-background-body"),
    surface: pickPair(webThemeCss, "color-background-surface"),
    popover: pickPair(webThemeCss, "color-background-popover"),
    foreground: pickPair(webThemeCss, "color-text-primary"),
    mutedForeground: pickPair(webThemeCss, "color-text-secondary"),
    border: pickPair(webThemeCss, "color-border"),
    radius: pickLength(webThemeCss, "radius-element"),
  };
}

const GENERATED_BANNER = `@generated by apps/site/scripts/build-theme.ts from ${paths.webThemeCss} — do not edit manually.
Re-run: bun run --filter @maruhi/site theme:build`;

const blumeTokenMap = (
  b: BrandTokens,
  mode: keyof ModePair,
): readonly (readonly [string, string])[] => [
  ["--blume-background", b.background[mode]],
  ["--blume-foreground", b.foreground[mode]],
  ["--blume-muted", b.surface[mode]],
  ["--blume-muted-foreground", b.mutedForeground[mode]],
  ["--blume-border", b.border[mode]],
  ["--blume-accent", b.accent[mode]],
  ["--blume-accent-foreground", b.onAccent[mode]],
  ["--blume-action", b.accent[mode]],
  ["--blume-code-background", b.popover[mode]],
];

/**
 * Blume の theme.css を描く。Blume は `:root` を light、`:root[data-theme="dark"]` を dark
 * として読む(theme.mode "system" ではインラインの起動スクリプトが OS 設定から
 * data-theme を立てる)。
 */
export function renderThemeCss(b: BrandTokens): string {
  const block = (selector: string, mode: keyof ModePair): string =>
    `${selector} {\n${blumeTokenMap(b, mode)
      .map(([name, value]) => `  ${name}: ${value.toLowerCase()};`)
      .join("\n")}\n}\n`;
  return `/*\n * ${GENERATED_BANNER.split("\n").join("\n * ")}\n *\n * Blume design tokens ← Astryx maruhi theme (ADR-0013: brand values live in apps/web/theme/).\n * Fonts are set from blume.config.ts (theme.fonts → Astro Fonts API), not here.\n */\n${block(":root", "light")}\n${block(':root[data-theme="dark"]', "dark")}\n:root {\n  --blume-radius: ${b.radius};\n}\n`;
}

const pair = (p: ModePair): string => `{ light: "${p.light}", dark: "${p.dark}" }`;

/** blume.config.ts / e2e が import する定数モジュールを描く(on-accent・surface は theme.css 側のみで使う)。 */
export function renderTokensTs(b: BrandTokens): string {
  return `// ${GENERATED_BANNER.split("\n").join("\n// ")}
// Brand tokens extracted from the Astryx maruhi theme (docs/notes/web-design-pass.md §3 / §4).

/** Vermilion accent — the red of the ㊙ mark (light) and its dark-mode tone. */
export const accent = ${pair(b.accent)} as const;

/** Page background (warm neutral body). */
export const background = ${pair(b.background)} as const;

/** Body text. */
export const foreground = ${pair(b.foreground)} as const;

/** Secondary text. */
export const mutedForeground = ${pair(b.mutedForeground)} as const;

/** Borders and dividers. */
export const border = ${pair(b.border)} as const;
`;
}

/**
 * ダークモード用ロゴ: apps/web/public/logo.svg(fill = light 側の accent)の fill を
 * dark 側の accent に置き換える。置換対象が見つからなければ前提(SVG の赤 = light accent —
 * DP1 裁定 A)が破れているので失敗させる。
 */
export function renderLogoDark(logoSvg: string, b: BrandTokens): string {
  const light = b.accent.light.toLowerCase();
  const re = new RegExp(`fill="${light}"`, "gi");
  if (!re.test(logoSvg)) {
    throw new Error(
      `apps/web/public/logo.svg: no fill="${b.accent.light}" found (DP1 裁定 A: SVG の赤 = light accent)`,
    );
  }
  const note = `<!-- @generated: apps/web/public/logo.svg with the fill swapped to the dark-mode accent (${b.accent.dark}) — see apps/site/scripts/build-theme.ts -->\n`;
  const swapped = logoSvg.replace(re, `fill="${b.accent.dark}"`);
  // 元の先頭コメントの直後(<svg の前)に由来を挿す
  const at = swapped.indexOf("<svg");
  return `${swapped.slice(0, at)}${note}${swapped.slice(at)}`;
}

/** 生成物一式(パス → 内容)。バイナリ資産は Buffer のまま複製する。 */
export function renderAll(repoRoot: string): ReadonlyMap<string, string | Buffer> {
  const css = readFileSync(join(repoRoot, paths.webThemeCss), "utf8");
  const brand = extractBrand(css);
  const logo = readFileSync(join(repoRoot, paths.webLogo), "utf8");
  const out = new Map<string, string | Buffer>();
  out.set(paths.themeCss, renderThemeCss(brand));
  out.set(paths.tokensTs, renderTokensTs(brand));
  out.set(paths.logoDark, renderLogoDark(logo, brand));
  for (const asset of copiedAssets) {
    out.set(`apps/site/public/${asset}`, readFileSync(join(repoRoot, "apps/web/public", asset)));
  }
  return out;
}
