/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/maruhi.ts
 * Command: astryx theme build theme/maruhi.ts --out theme/maruhi.css
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

/// <reference path="./maruhi.variants.d.ts" />
import type { DefinedTheme } from "@astryxdesign/core/theme";
export declare const maruhiTheme: DefinedTheme;
