/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/maruhi.ts
 * Command: astryx theme build theme/maruhi.ts --out theme/maruhi.css
 * Generated: 2026-08-01T08:43:43.288Z
 */

// Generated by astryx theme build
export {};

declare module "@astryxdesign/core/Badge" {
  interface BadgeVariantMap {
    gray: true;
  }
}
