/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/maruhi.ts
 * Command: astryx theme build theme/maruhi.ts --out theme/maruhi.css
 * CLI: @astryxdesign/cli@0.3.0
 * Core: @astryxdesign/core@0.3.0
 */

// Generated by astryx theme build
export {};

declare module "@astryxdesign/core/Badge" {
  interface BadgeVariantMap {
    gray: true;
  }
}
