// Repository anchor (CRYPTO_SPEC §6.3 out-of-band anchor (b)).
//
// A non-secret anchor file committed to the project's source repository:
// the genesis hash (= projectId), the verified head (hash + seq), and each
// environment's "chain-derived current epoch at that time". The receiving
// client of a workload lease (§9.1) (ci-run.ts) accepts, on top of chain
// verification, only a view that "contains the anchor's head and has
// environment epochs at or above the anchor" (SHOULD). This makes rollback
// distribution to CI — the weakest client, floorless, automated, and
// unattended — detectable (e.g. distributing an old view after an incident
// rotation so an already-leaked credential keeps being re-deployed).
//
// Generated by `maruhi project anchor` (from a member's verified view to
// stdout). It contains only hashes, sequence numbers, and epoch numbers —
// no plaintext values or key material (compatible with the diskless
// invariant — what writes it is the user's redirect, and it is non-secret).

import { decodeEnvironmentId, isEnvironmentId, isProjectId, type ProjectId } from "@maruhi/core";
import { Effect, Schema } from "effect";

import type { VerifiedProject } from "./chain-sync.ts";
import { cliError, type CliError } from "./errors.ts";
import {
  Hex64,
  JsonRecord,
  parseJsonRecord,
  PositiveInt,
  readNamedFile,
  recordKeysMatch,
} from "./json-record.ts";

/** A repository anchor file (CRYPTO_SPEC §6.3 out-of-band anchor (b)). */
export interface RepositoryAnchor {
  readonly version: 1;
  /** Genesis hash (= projectId — §6.4). */
  readonly projectId: ProjectId;
  /** The verified chain head at generation time. */
  readonly headSeq: number;
  readonly headHashHex: string;
  /** Environment ID → chain-derived current epoch at generation time. */
  readonly environments: Readonly<Record<string, number>>;
}

/** Builds an anchor from a verified view (`maruhi project anchor`). */
export function buildRepositoryAnchor(verified: VerifiedProject): RepositoryAnchor {
  const environments: Record<string, number> = {};
  // Sort by environment ID ascending for deterministic output (keeps committed diffs stable)
  for (const environmentId of [...verified.state.environments.keys()].toSorted()) {
    const environment = isEnvironmentId(environmentId)
      ? verified.state.environments.get(decodeEnvironmentId(environmentId))
      : undefined;
    if (environment !== undefined) {
      environments[environmentId] = environment.currentEpoch;
    }
  }
  return {
    version: 1,
    projectId: verified.projectId,
    headSeq: verified.state.headSeq,
    headHashHex: verified.state.headHashHex,
    environments,
  };
}

/** The anchor's file representation (commit-friendly pretty JSON + trailing newline). */
export function formatRepositoryAnchor(anchor: RepositoryAnchor): string {
  return `${JSON.stringify(anchor, null, 2)}\n`;
}

// The environments field: { environmentId: epoch } (id keys, positive integer values).
const AnchorEnvironments = Schema.Record(Schema.String, PositiveInt).check(
  recordKeysMatch(isEnvironmentId),
);

/** Interprets the top-level shape and version / projectId (a reason string when invalid). */
function anchorRecordOf(content: string): Record<string, unknown> | string {
  const record = parseJsonRecord(content);
  if (typeof record === "string") {
    return record;
  }
  if (record["version"] !== 1) {
    return "unsupported anchor version (expected 1)";
  }
  return record;
}

/** Interprets the anchor JSON (a reason string when invalid). */
function parseRepositoryAnchor(content: string): RepositoryAnchor | string {
  const record = anchorRecordOf(content);
  if (typeof record === "string") {
    return record;
  }
  const projectId = record["projectId"];
  if (!(typeof projectId === "string" && isProjectId(projectId))) {
    return "projectId must be the genesis hash (64 hex digits)";
  }
  const headSeq = record["headSeq"];
  if (!Schema.is(PositiveInt)(headSeq)) {
    return "headSeq must be a positive integer";
  }
  const headHashHex = record["headHashHex"];
  if (!Schema.is(Hex64)(headHashHex)) {
    return "headHashHex must be 64 lowercase hex digits";
  }
  const environments = record["environments"];
  if (!Schema.is(JsonRecord)(environments)) {
    return "environments must be an object of { environmentId: epoch }";
  }
  if (!Schema.is(AnchorEnvironments)(environments)) {
    return "environments must map environment IDs to positive integer epochs";
  }
  return { version: 1, projectId, headSeq, headHashHex, environments };
}

/** Reads `--anchor <file>` (generated by `maruhi project anchor`). */
export const loadRepositoryAnchor = Effect.fn("anchor.loadRepositoryAnchor")(function* (
  path: string,
): Effect.fn.Return<RepositoryAnchor, CliError> {
  const content = yield* readNamedFile(
    path,
    cliError("Cannot read the --anchor file (check the path)"),
  );
  const parsed = parseRepositoryAnchor(content);
  if (typeof parsed === "string") {
    return yield* Effect.fail(
      cliError(
        `The --anchor file is invalid: ${parsed}. Regenerate it with \`maruhi project anchor\``,
      ),
    );
  }
  return parsed;
});

/**
 * Anchor check (§6.3 (b) / the §9.1 verification obligation (2)): the
 * verified view must (i) share the anchor's genesis, (ii) contain the
 * anchor's pinned head at that seq, and (iii) have each anchored
 * environment's chain-derived current epoch at or above the anchor. A
 * mismatch is a contradiction between a signature-verified artifact and a
 * committed anchor = evidence of rollback or fork distribution, so refuse it
 * (the strong side of SHOULD — same shape as checkInviteAnchor).
 */
export const checkRepositoryAnchor = Effect.fn("anchor.checkRepositoryAnchor")(function* (input: {
  readonly anchor: RepositoryAnchor;
  readonly verified: VerifiedProject;
}): Effect.fn.Return<void, CliError> {
  const { anchor, verified } = input;
  const evidenceHint =
    "The verification material is the committed anchor file plus the distributed chain (CRYPTO_SPEC §6.3 out-of-band anchor (b))";
  if (anchor.projectId !== verified.projectId) {
    return yield* Effect.fail(
      cliError(
        `Repository-anchor check failed: the anchor's genesis hash does not match the pinned project ID. The anchor file belongs to a different project, or the CI configuration is wrong. ${evidenceHint}`,
      ),
    );
  }
  if (verified.history.entryHashAt(anchor.headSeq) !== anchor.headHashHex) {
    return yield* Effect.fail(
      cliError(
        `Repository-anchor check failed: the distributed chain does not contain the anchored head (seq=${anchor.headSeq}). This suggests a server-side rollback or fork distribution — do not trust this response. ${evidenceHint}`,
      ),
    );
  }
  for (const [environmentId, anchoredEpoch] of Object.entries(anchor.environments)) {
    // An environment's existence itself is chain-derived (§6.2). A missing
    // anchored environment means the whole segment containing
    // create_environment was rolled back, so it is the same evidence
    // (the wording differs — a regression and an absence are different
    // observed facts)
    const environment = isEnvironmentId(environmentId)
      ? verified.state.environments.get(decodeEnvironmentId(environmentId))
      : undefined;
    if (environment === undefined) {
      return yield* Effect.fail(
        cliError(
          `Repository-anchor check failed: anchored environment ${environmentId} does not exist on the distributed chain. This suggests a rollback past the environment's creation — do not trust this response. ${evidenceHint}`,
        ),
      );
    }
    if (environment.currentEpoch < anchoredEpoch) {
      return yield* Effect.fail(
        cliError(
          `Repository-anchor check failed: environment ${environmentId} has a chain-derived epoch below the anchored epoch (${anchoredEpoch}). This suggests distribution of a pre-rotation view (a leaked credential could be re-deployed) — do not trust this response. ${evidenceHint}`,
        ),
      );
    }
  }
});
