// @generated by apps/site/scripts/build-theme.ts from apps/web/theme/maruhi.css — do not edit manually.
// Re-run: bun run --filter @maruhi/site theme:build
// Brand tokens extracted from the Astryx maruhi theme (docs/notes/web-design-pass.md §3 / §4).

/** Vermilion accent — the red of the ㊙ mark (light) and its dark-mode tone. */
export const accent = { light: "#C1330B", dark: "#FF693C" } as const;

/** Page background (warm neutral body). */
export const background = { light: "#FFEDE7", dark: "#1B0D07" } as const;

/** Body text. */
export const foreground = { light: "#241915", dark: "#F0DFD9" } as const;

/** Secondary text. */
export const mutedForeground = { light: "#56423C", dark: "#BDA69F" } as const;

/** Borders and dividers. */
export const border = { light: "#2419151A", dark: "#FFEDE71A" } as const;
